### ISSUE TITLE
/api/auth/token endpoint

### ISSUE THREAD

**Issue by paulyoung** [the-grid/Disc#14]
#11 introduced the notion of being able to "delete" a "token". It spoke of "revoking" a token and "removing scopes granted" as the mechanism for logging out of the API.

In my mind revoking an access token and logging out are 2 very different things, which is why I didn't include this in #13.

**Comment by nickvelloff** [comment]
Here is a ticket regarding this, which is a good place to get an understanding of this.
https://github.com/the-grid/the-grid-account/issues/69#issuecomment-168238478

**Comment by nickvelloff** [comment]
cc @trustmaster

**Comment by nickvelloff** [comment]
Here is my understanding of a typical OAuth multi-client setup, but do correct me if I am wrong.
- Users are granted a client (iOS) + User specific access token
- A token may be "revoked" for a particular client, but would not affect other granted tokens for that user for other clients
- I do not understand why scopes would be invalidated, only the client specific token
- If a client attempts a new provider for access token exchange, another would be provided specific to the client

@trustmaster is this a typical pattern and are we in line with it?

**Comment by trustmaster** [comment]
I'd say that revoking an API token is a "disconnect" rather than "logout". If you need to logout from the client, you should just destroy the client session without disconnecting the API token. Next time you need to log in, you will be able to do so using Provider auth and as the result you will receive the same (updated) token as prior to logout, with all the scopes in place.

API tokens are per user per client. Using multiple identity providers to obtain them doesn't generate new API tokens, they all share the same token for current client (e.g. iOS).

**Comment by nickvelloff** [comment]
@trustmaster OK this is what we are currently doing.
For my own understanding, what is the use case for a "disconnect"?

**Comment by trustmaster** [comment]
@nickvelloff "disconnect" is likely to be a rare animal, but here are 2 example cases for it:

 - Testing the scope dialogs and authorization from scratch, revoke a token and login again.
 - If token has leaked and it has to be invalidated.

**Comment by nickvelloff** [comment]
Thanks @trustmaster. I wanted to be sure I was clear on the intended usage and it appears I do not need to utilize this quite yet. The native login, add/remove identity are working great and I think I can quite bugging you for a while.

**Comment by trustmaster** [comment]
@nickvelloff then it will be my turn to bug you with "Login via email" soon :wink:

**Comment by nickvelloff** [comment]
@trustmaster Oh I missed that this was on the radar. This will be good. There is exactly 1 review of the iOS app and it is 1 star. I really don't even understand what he means :fearful: 
<img width="905" alt="screenshot 2016-01-05 12 01 36" src="https://cloud.githubusercontent.com/assets/885369/12126142/3e51ac84-b3a4-11e5-960e-5b4892459ec5.png">
