### ISSUE TITLE
Missing provider entries for GitHub

### ISSUE THREAD

**Issue by paulyoung** [the-grid/Disc#3]
As explained by @trustmaster in https://github.com/the-grid/DemoDisc/issues/1#issuecomment-150682454

**Comment by paulyoung** [comment]
I think the only potential issue I can see with this is that `Provider` is also used to construct a login URL: https://github.com/the-grid/Disc/blob/master/Disc/Networking/Authorization/CreateLoginUrl.swift#L10

As opposed to `/login/authorize/github` I'm not sure if `/login/authorize/github_public` and `/login/authorize/github_private` are valid.

@trustmaster can you confirm?

**Comment by trustmaster** [comment]
@paulyoung yes, we have `/login/authorize/*` endpoints for all 3 GitHub provider values.

**Comment by paulyoung** [comment]
Great. I actually just tried and it seemed to work but thanks for confirming.

**Comment by paulyoung** [comment]
These were added in d2f288bd3e017b98a03c550f3545c31ac9019df1.
